#!/bin/bash

###############################################################################
# ProfilePhotoAI Frontend Deployment Script
# 
# Usage:
#   ./scripts/deploy-frontend.sh [environment]
#   
# Example:
#   ./scripts/deploy-frontend.sh dev
#   ./scripts/deploy-frontend.sh prod
###############################################################################

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
ENVIRONMENT=${1:-dev}
VALID_ENVS=("dev" "staging" "prod")

if [[ ! " ${VALID_ENVS[@]} " =~ " ${ENVIRONMENT} " ]]; then
    echo -e "${RED}❌ Invalid environment: ${ENVIRONMENT}${NC}"
    echo "Valid environments: ${VALID_ENVS[@]}"
    exit 1
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}ProfilePhotoAI Frontend Deployment${NC}"
echo -e "${BLUE}Environment: ${ENVIRONMENT}${NC}"
echo -e "${BLUE}========================================${NC}"

# Get stack outputs
STACK_NAME="profile-photo-ai-${ENVIRONMENT}"
echo -e "\n${YELLOW}📋 Fetching stack information...${NC}"

# Get bucket name and CloudFront distribution ID
FRONTEND_BUCKET=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" \
    --output text)

CLOUDFRONT_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
    --output text)

API_ENDPOINT=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" \
    --output text)

USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
    --output text)

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
    --output text)

WEBSITE_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" \
    --output text)

if [ -z "$FRONTEND_BUCKET" ] || [ -z "$CLOUDFRONT_ID" ]; then
    echo -e "${RED}❌ Failed to get stack outputs. Make sure the stack is deployed.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Stack information retrieved:${NC}"
echo -e "  Frontend Bucket: ${FRONTEND_BUCKET}"
echo -e "  CloudFront ID: ${CLOUDFRONT_ID}"
echo -e "  API Endpoint: ${API_ENDPOINT}"
echo -e "  Website URL: ${WEBSITE_URL}"

# Navigate to frontend directory
cd "$(dirname "$0")/../frontend"

# Get Cognito Domain from CloudFormation
USER_POOL_DOMAIN=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='UserPoolDomain'].OutputValue" \
    --output text)

# Create .env.production file
echo -e "\n${YELLOW}🔧 Creating prod config...${NC}"
cat > .env.production << EOF
# Auto-generated by deploy-frontend.sh
# DO NOT COMMIT THIS FILE

REACT_APP_API_ENDPOINT=${API_ENDPOINT}
REACT_APP_AWS_REGION=ap-northeast-2
REACT_APP_COGNITO_USER_POOL_ID=${USER_POOL_ID}
REACT_APP_COGNITO_CLIENT_ID=${USER_POOL_CLIENT_ID}
REACT_APP_COGNITO_DOMAIN=${USER_POOL_DOMAIN}
REACT_APP_REDIRECT_URI=${WEBSITE_URL}/callback
REACT_APP_ENVIRONMENT=${ENVIRONMENT}
EOF

echo -e "${GREEN}✅ Production config created${NC}"

# Install dependencies
echo -e "\n${YELLOW}📦 Installing dependencies...${NC}"
npm install

# Build React app with environment variables
echo -e "\n${YELLOW}🏗️  Building React app...${NC}"

# Export environment variables for build
export REACT_APP_API_ENDPOINT="${API_ENDPOINT}"
export REACT_APP_AWS_REGION="ap-northeast-2"
export REACT_APP_COGNITO_USER_POOL_ID="${USER_POOL_ID}"
export REACT_APP_COGNITO_CLIENT_ID="${USER_POOL_CLIENT_ID}"
export REACT_APP_COGNITO_DOMAIN="${USER_POOL_DOMAIN}"
export REACT_APP_REDIRECT_URI="${WEBSITE_URL}/callback"
export REACT_APP_ENVIRONMENT="${ENVIRONMENT}"

npm run build

if [ ! -d "build" ]; then
    echo -e "${RED}❌ Build directory not found${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Build completed${NC}"

# Sync to S3
echo -e "\n${YELLOW}☁️  Uploading to S3...${NC}"
aws s3 sync build/ "s3://${FRONTEND_BUCKET}/" \
    --delete \
    --cache-control "public,max-age=31536000,immutable" \
    --exclude "index.html" \
    --exclude "asset-manifest.json" \
    --exclude "manifest.json"

# Upload index.html and manifest files with no-cache
aws s3 cp build/index.html "s3://${FRONTEND_BUCKET}/index.html" \
    --cache-control "public,max-age=0,must-revalidate" \
    --content-type "text/html"

if [ -f "build/manifest.json" ]; then
    aws s3 cp build/manifest.json "s3://${FRONTEND_BUCKET}/manifest.json" \
        --cache-control "public,max-age=0,must-revalidate" \
        --content-type "application/json"
fi

if [ -f "build/asset-manifest.json" ]; then
    aws s3 cp build/asset-manifest.json "s3://${FRONTEND_BUCKET}/asset-manifest.json" \
        --cache-control "public,max-age=0,must-revalidate" \
        --content-type "application/json"
fi

echo -e "${GREEN}✅ Files uploaded to S3${NC}"

# Invalidate CloudFront cache
echo -e "\n${YELLOW}🔄 Invalidating CloudFront cache...${NC}"
INVALIDATION_ID=$(aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_ID" \
    --paths "/*" \
    --query 'Invalidation.Id' \
    --output text)

echo -e "${GREEN}✅ CloudFront invalidation created: ${INVALIDATION_ID}${NC}"
echo -e "${YELLOW}⏳ Waiting for invalidation to complete (this may take a few minutes)...${NC}"

aws cloudfront wait invalidation-completed \
    --distribution-id "$CLOUDFRONT_ID" \
    --id "$INVALIDATION_ID"

echo -e "${GREEN}✅ CloudFront cache invalidated${NC}"

# Summary
echo -e "\n${BLUE}========================================${NC}"
echo -e "${GREEN}✅ Deployment Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo -e "\n${GREEN}🌐 Website URL:${NC} ${WEBSITE_URL}"
echo -e "\n${YELLOW}📝 Next Steps:${NC}"
echo -e "  1. Visit ${WEBSITE_URL} to test the website"
echo -e "  2. Check CloudFront logs if you encounter issues"
echo -e "  3. Monitor API Gateway and Lambda logs"

# Clean up
rm -f .env.production

echo -e "\n${GREEN}Done!${NC}"
